name: CI

env:
  NODE_OPTIONS: --max-old-space-size=6144

on:
  push:
    branches: [main, master]
    paths-ignore:
      - "examples/**"
      - "scripts/**"
  pull_request:
    branches: [main, master]
    paths-ignore:
      - "examples/**"
      - "scripts/**"

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [16.x, 20.x]
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.15.8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      # We use week in the turbo cache key to keep the cache from infinitely growing
      - name: Get cache expires mark (non-windows)
        if: runner.os != 'Windows'
        id: expires-non-windows
        run: echo "EXPIRES_WEEK_MARK=$(date +%U)" >> $GITHUB_OUTPUT
      - name: Get cache expires mark (windows)
        if: runner.os == 'Windows'
        id: expires-windows
        run: echo "EXPIRES_WEEK_MARK=$(date +%U)" >> $env:GITHUB_OUTPUT

      - name: Setup Turbo cache
        uses: actions/cache@v3
        with:
          path: .turbo
          key: turbo-${{ github.job }}-${{ runner.os }}-node${{ matrix.node-version }}-${{ github.ref_name }}-${{ (runner.os == 'Windows' && steps.expires-windows.outputs.EXPIRES_WEEK_MARK) || steps.expires-non-windows.outputs.EXPIRES_WEEK_MARK }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.job }}-${{ runner.os }}-node${{ matrix.node-version }}-

      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build

      - name: Type check
        run: pnpm typecheck

      - name: Unit tests
        run: pnpm test:ci

      - name: E2E tests
        run: pnpm test:ci:e2e
